name: tikd
description: Tools for writing TIKZ with modern programming supports from Dart.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.9.0
  process_run: ^0.13.3
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
